version: 2
updates:
  # maintain GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
  # maintain npm dependencies
  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
