version: 2
updates:
  # maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
  # maintain npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
